parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: '%env(resolve:DB_DRIVER)%'
        server_version: '11.1'
        charset: utf8
        default_table_options:
            charset: '%env(resolve:DB_CHARSET)%'
            collate: '%env(resolve:DB_COLLATE)%'

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            metadata_cache_driver:
                type: service
                id: doctrine.system_cache_provider
            query_cache_driver:
                type: service
                id: doctrine.system_cache_provider
            result_cache_driver:
                type: service
                id: doctrine.result_cache_provider

    services:
        doctrine.result_cache_provider:
            class: Symfony\Component\Cache\DoctrineProvider
            public: false
            arguments:
                - '@doctrine.result_cache_pool'
        doctrine.system_cache_provider:
            class: Symfony\Component\Cache\DoctrineProvider
            public: false
            arguments:
                - '@doctrine.system_cache_pool'

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
