parameters:
  verbou:
    a1:
      bremañ:
      - ["an"]
      - ["ez"]
      - [""]
      - ["omp"]
      - ["it"]
      - ["ont"]
      - ["er"]
      tremenet_ledan:
      - ["en"]
      - ["es"]
      - ["e"]
      - ["emp"]
      - ["ec'h"]
      - ["ent"]
      - ["ed"]
      tremenet_strizh:
      - ["is"]
      - ["jout"]
      - ["as"]
      - ["jomp"]
      - ["joc'h"]
      - ["jont"]
      - ["jod"]
      da_zont:
      - ["in"]
      - ["i"]
      - ["o"]
      - ["imp"]
      - ["ot", "oc'h"]
      - ["int"]
      - ["or"]
      gallus:
      - ["fen"]
      - ["fes"]
      - ["fe"]
      - ["femp"]
      - ["fec'h"]
      - ["fent"]
      - ["fed"]
      dichallus:
      - ["jen"]
      - ["jes"]
      - ["je"]
      - ["jemp"]
      - ["jec'h"]
      - ["jent"]
      - ["jed"]
      kadarnaat:
      - [] 
      - [""]
      - ["et"]
      - ["omp"]
      - ["it"]
      - ["ent"]
      - []
      nach:
      - []
      - []
      - []
      - []
      - []
      - []
      - []
    d1:
      gwan: et
      bremañ:
      - ["an"]
      - ["ez"]
      - [""]
      - ["omp"]
      - ["it"]
      - ["ont"]
      - ["er"]
      tremenet_ledan:
      - ["en"]
      - ["es"]
      - ["e"]
      - ["emp"]
      - ["ec'h"]
      - ["ent"]
      - ["ed"]
      tremenet_strizh:
      - ["is"]
      - ["jout"]
      - ["as"]
      - ["jomp"]
      - ["joc'h"]
      - ["jont"]
      - ["jod"]
      da_zont:
      - ["in"]
      - ["i"]
      - ["o"]
      - ["imp"]
      - ["ot", "oc'h"]
      - ["int"]
      - ["or"]
      gallus:
      - ["fen"]
      - ["fes"]
      - ["fe"]
      - ["femp"]
      - ["fec'h"]
      - ["fent"]
      - ["fed"]
      dichallus:
      - ["jen"]
      - ["jes"]
      - ["je"]
      - ["jemp"]
      - ["jec'h"]
      - ["jent"]
      - ["jed"]
      kadarnaat:
      - []
      - ['']
      - ["et"]
      - ["omp"]
      - ["it"]
      - ["ent"]
      - []
      nach:
      - []
      - []
      - []
      - []
      - []
      - []
      - []
    d2:
      gwan: et
      bremañ:
      - ["an"]
      - ["ez"]
      - ['']
      - ["omp"]
      - ["it"]
      - ["ont"]
      - ["er"]
      tremenet_ledan:
      - ["en"]
      - ["es"]
      - ["e"]
      - ["emp"]
      - ["ec'h"]
      - ["ent"]
      - ["ed"]
      tremenet_strizh:
      - ["is"]
      - ["jout"]
      - ["as"]
      - ["jomp"]
      - ["joc'h"]
      - ["jont"]
      - ["jod"]
      da_zont:
      - ["in"]
      - ["i"]
      - ['o', 'y']
      - ["imp"]
      - ['ot', "oc'h"]
      - ["int"]
      - ["or"]
      gallus:
      - ["fen"]
      - ["fes"]
      - ["fe"]
      - ["femp"]
      - ["fec'h"]
      - ["fent"]
      - ["fed"]
      dichallus:
      - ["jen"]
      - ["jes"]
      - ["je"]
      - ["jemp"]
      - ["jec'h"]
      - ["jent"]
      - ["jed"]
      kadarnaat:
      - []
      - ['']
      - ["et"]
      - ["omp"]
      - ["it"]
      - ["ent"]
      - []
      nach:
      - []
      - []
      - []
      - []
      - []
      - []
      - []
    d3:
      gwan: et
      bremañ:
      - ["an"]
      - ["ez"]
      - ["a"]
      - ["omp"]
      - ["it"]
      - ["ont"]
      - ["er"]
      tremenet_ledan:
      - ["en"]
      - ["es"]
      - ["e"]
      - ["emp"]
      - ["ec'h"]
      - ["ent"]
      - ["ed"]
      tremenet_strizh:
      - ['is', 'jon']
      - ["jout"]
      - ["as"]
      - ["jomp"]
      - ["joc'h"]
      - ["jont"]
      - ["jod"]
      da_zont:
      - ["in"]
      - ["i"]
      - ['o', 'ay']
      - ["imp"]
      - ['ot', "oc'h"]
      - ["int"]
      - ["or"]
      gallus:
      - ["fen"]
      - ["fes"]
      - ["fe"]
      - ["femp"]
      - ["fec'h"]
      - ["fent"]
      - ["fed"]
      dichallus:
      - ["jen"]
      - ["jes"]
      - ["je"]
      - ["jemp"]
      - ["jec'h"]
      - ["jent"]
      - ["jed"]
      kadarnaat:
      - []
      - ["a"]
      - ["et"]
      - ["omp"]
      - ["it"]
      - ["ent"]
      - []
      nach:
      - []
      - []
      - []
      - []
      - []
      - []
      - []
    d4:
      gwan: iet
      bremañ:
      - ["ian"]
      - ["iez"]
      - ['']
      - ["iomp"]
      - ["it"]
      - ["iont"]
      - ["ier"]
      tremenet_ledan:
      - ["ien"]
      - ["ies"]
      - ["ie"]
      - ["iemp"]
      - ["iec'h"]
      - ["ient"]
      - ["ied"]
      tremenet_strizh:
      - ['is', 'jon']
      - ["jout"]
      - ["ias"]
      - ["jomp"]
      - ["joc'h"]
      - ["jont"]
      - ["jod"]
      da_zont:
      - ["in"]
      - ["i"]
      - ["io"]
      - ["imp"]
      - ['iot', "oc'h"]
      - ["int"]
      - ["ior"]
      gallus:
      - ["fen"]
      - ["fes"]
      - ["fe"]
      - ["femp"]
      - ["fec'h"]
      - ["fent"]
      - ["fed"]
      dichallus:
      - ["jen"]
      - ["jes"]
      - ["je"]
      - ["jemp"]
      - ["jec'h"]
      - ["jent"]
      - ["jed"]
      kadarnaat:
      - []
      - ['']
      - ["iet"]
      - ["iomp"]
      - ["it"]
      - ["ient"]
      - []
      nach:
      - []
      - []
      - []
      - []
      - []
      - []
      - []
    d5:
      gwan: et
      bremañ:
      - ["lian"]
      - ["liez"]
      - ["ilh"]
      - ["liomp"]
      - ["ilhit"]
      - ["liont"]
      - ["lier"]
      tremenet_ledan:
      - ["lien"]
      - ["lies"]
      - ["lie"]
      - ["liemp"]
      - ["liec'h"]
      - ["lient"]
      - ["lied"]
      tremenet_strizh:
      - ['ilhis', 'ilhjon']
      - ["ilhjout"]
      - ["lias"]
      - ["ilhjomp"]
      - ["ilhjoc'h"]
      - ["ilhjont"]
      - ["ilhjod"]
      da_zont:
      - ["ilhin"]
      - ["ilhi"]
      - ["ilho"]
      - ["ilhimp"]
      - ['ilhot', "ilhoc'h"]
      - ["ilhint"]
      - ["ilhor"]
      gallus:
      - ["ilhfen"]
      - ["ilhfes"]
      - ["ilhfe"]
      - ["ilhfemp"]
      - ["ilhfec'h"]
      - ["ilhfent"]
      - ["ilhfed"]
      dichallus:
      - ["ilhjen"]
      - ["ilhjes"]
      - ["ilhje"]
      - ["ilhjemp"]
      - ["ilhjec'h"]
      - ["ilhjent"]
      - ["ilhjed"]
      kadarnaat:
      - []
      - ["ilh"]
      - ["liet"]
      - ["liomp"]
      - ["ilhit"]
      - ["lient"]
      - []
      nach:
      - []
      - []
      - []
      - []
      - []
      - []
      - []
    d6:
      gwan: niet
      bremañ:
      - ["nian"]
      - ["niez"]
      - ["gn"]
      - ["niomp"]
      - ["gnit"]
      - ["niont"]
      - ["nier"]
      tremenet_ledan:
      - ["nien"]
      - ["nies"]
      - ["nie"]
      - ["niemp"]
      - ["niec'h"]
      - ["nient"]
      - ["nied"]
      tremenet_strizh:
      - ['gnis', 'jont']
      - ["gnjout"]
      - ["nias"]
      - ["gnjomp"]
      - ["gnjoc'h"]
      - ["gnjont"]
      - ["gnjod"]
      da_zont:
      - ["gnin"]
      - ["gni"]
      - ["nio"]
      - ["gnimp"]
      - ['niot', "nioc'h"]
      - ["gnint"]
      - ["nior"]
      gallus:
      - ["gnfen"]
      - ["gnfes"]
      - ["gnfe"]
      - ["gnfemp"]
      - ["gnfec'h"]
      - ["gnfent"]
      - ["gnfed"]
      dichallus:
      - ["gnjen"]
      - ["gnjes"]
      - ["gnje"]
      - ["gnjemp"]
      - ["gnjec'h"]
      - ["gnjent"]
      - ["gnjed"]
      kadarnaat:
      - []
      - ["gn"]
      - ["niet"]
      - ["niomp"]
      - ["gnit"]
      - ["nient"]
      - []
      nach:
      - []
      - []
      - []
      - []
      - []
      - []
      - []
    d7:
      gwan: et
      bremañ:
      - ["an"]
      - ["aez"]
      - ["a"]
      - ["eomp"]
      - ["it"]
      - ["eont"]
      - ["eer"]
      tremenet_ledan:
      - ["aen"]
      - ["aes"]
      - ["ae"]
      - ["aemp"]
      - ["aec'h"]
      - ["aent"]
      - ["aed"]
      tremenet_strizh:
      - ['is', 'rejon']
      - ["ejout"]
      - ["reas"]
      - ["ejomp"]
      - ["ejoc'h"]
      - ["ejont"]
      - ["ejod"]
      da_zont:
      - ["in"]
      - ["i"]
      - ['aio', 'ay']
      - ["aimp"]
      - ['eot', "eoc'h"]
      - ["aint"]
      - ["eor"]
      gallus:
      - ["afen"]
      - ["afes"]
      - ["afe"]
      - ["afemp"]
      - ["afec'h"]
      - ["afent"]
      - ["afed"]
      dichallus:
      - ["ajen"]
      - ["ajes"]
      - ["aje"]
      - ["ajemp"]
      - ["ajec'h"]
      - ["ajent"]
      - ["ajed"]
      kadarnaat:
      - []
      - ["a"]
      - ["aet"]
      - ["eomp"]
      - ["it"]
      - ["aent"]
      - []
      nach:
      - []
      - []
      - []
      - []
      - []
      - []
      - []
    gouzout:
      gwan: gouezet
      bremañ:
      - ["gouzon"]
      - ["gouzout"]
      - ["goar"]
      - ["gouzomp"]
      - ["gouzoc'h"]
      - ["gouzont"]
      - ["gouzer"]
      tremenet_ledan:
      - ["gouien"]
      - ["gouies"]
      - ["gouie"]
      - ["gouiemp"]
      - ["gouiec'h"]
      - ["gouient"]
      - ["gouied"]
      tremenet_strizh:
      - ["gouezis"]
      - ["gouezjout"]
      - ["gouezas"]
      - ["gouezjomp"]
      - ["gouezjoc'h"]
      - ["gouezjont"]
      - ["gouezjod"]
      da_zont:
      - ["gouezin"]
      - ["gouezi"]
      - ["gouezo"]
      - ["gouezimp"]
      - ['gouezot', "gouezoc'h"]
      - ["gouezint"]
      - ["gouezor"]
      gallus:
      - ["goufen"]
      - ["goufes"]
      - ["goufe"]
      - ["goufemp"]
      - ["goufec'h"]
      - ["goufent"]
      - ["goufed"]
      dichallus:
      - ["gouijen"]
      - ["gouijes"]
      - ["gouije"]
      - ["gouijemp"]
      - ["gouijec'h"]
      - ["gouijent"]
      - ["gouijed"]
      kadarnaat:
      - []
      - ["gouez"]
      - ["gouezet"]
      - ["gouezomp"]
      - ["gouezit"]
      - ["gouezent"]
      - []
      nach:
      - []
      - []
      - []
      - []
      - []
      - []
      - []
    dont:
      bremañ:
      - ["an"]
      - ["ez"]
      - ''
      - ["omp"]
      - ["it"]
      - ["ont"]
      - ["er"]
      tremenet_ledan:
      - ["en"]
      - ["es"]
      - ["e"]
      - ["emp"]
      - ["ec'h"]
      - ["ent"]
      - ["ed"]
      tremenet_strizh:
      - ["is"]
      - ["jout"]
      - ["as"]
      - ["jomp"]
      - ["joc'h"]
      - ["jont"]
      - ["jod"]
      da_zont:
      - ["in"]
      - ["i"]
      - [ 'io', 'y']
      - ["imp"]
      - ['ot', "oc'h"]
      - ["int"]
      - ["or"]
      gallus:
      - ["fen"]
      - ["fes"]
      - ["fe"]
      - ["femp"]
      - ["fec'h"]
      - ["fent"]
      - ["fed"]
      dichallus:
      - ["jen"]
      - ["jes"]
      - ["je"]
      - ["jemp"]
      - ["jec'h"]
      - ["jent"]
      - ["jed"]
      kadarnaat:
      - []
      - ["s"]
      - ["et"]
      - ["omp"]
      - ["it"]
      - ["ent"]
      - []
      nach:
      - []
      - []
      - []
      - []
      - []
      - []
      - []
