# https://github.com/maxpou/docker-symfony/blob/master/docker-compose.yml
version: '3.2'

services:
    
    database:
      image: postgres:12
      working_dir: /srv
      volumes:
        - database:/usr/local/var/postgres
        - ./docker/database:/database
      ports:
        - "127.0.0.1:8432:5432"
      networks:
        - displeger
      environment:
        - POSTGRES_PASSWORD=displeger
        - POSTGRES_DB=displeger

    php:
        build:
            context: docker/php
        working_dir: /srv
        volumes:
            - ./:/srv/
        networks:
          - displeger

    node:
        build:
            context: ./docker/node
        working_dir: /srv
        volumes:
            - ./:/srv/
        
    nginx:
        image: nginx:1-alpine
        volumes:
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/srv/:ro
        ports:
            - "8000:80"
        networks:
          - displeger

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
            - "1025:1025"
        networks:
          - displeger

volumes:
    database: ~

networks:
    displeger: ~